# In .travis.yml
language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements/requirements.txt
script:
  - cd language_of_love
  - python -m unittest discover -s tests
  - cd ..
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
