class Audio():
    practice_start = "<audio src='https://s3.amazonaws.com/language-of-love/lecturer-practice-start.mp3'/>"
    Q_e_lecturer_like_chocolate = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-do-u-like-chocolate.mp3'/>"
    Q_e_lecturer_like_coffee = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-do-u-like-coffee.mp3'/>"
    Q_e_lecturer_like_flower = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-do-u-like-flowers.mp3'/>"
    Q_e_lecturer_like_drink = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-do-u-like-drink.mp3'/>"
    Q_e_lecturer_like_travel = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-do-u-like-travel.mp3'/>"
    Q_e_lecturer_what_name = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-whats-ur-name.mp3'/>"
    Q_e_lecturer_what_profession = "<audio src='https://s3.amazonaws.com/language-of-love/english-lecturer-whats-ur-profession.mp3'/>"

    Q_s_lecturer_like_chocolate = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-do-u-like-chocolate.mp3'/>"
    Q_s_lecturer_like_coffee = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-do-u-like-coffee.mp3'/>"
    Q_s_lecturer_like_flower = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-do-u-like-flowers.mp3'/>"
    Q_s_lecturer_like_drink = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-do-u-like-drink.mp3'/>"
    Q_s_lecturer_like_travel = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-do-u-like-travel.mp3'/>"
    Q_s_lecturer_what_name = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-whats-ur-name.mp3'/>"
    Q_s_lecturer_what_profession = "<audio src='https://s3.amazonaws.com/language-of-love/spanish-lecturer-whats-ur-profession.mp3'/>"
    # hgjaghj
    point = "<audio src='https://s3.amazonaws.com/language-of-love/point.mp3'/>"
    cricket_sound = "<audio src='https://s3.amazonaws.com/language-of-love/cricket_sound.mp3'/>"
    welcome = "<audio src ='https://s3.amazonaws.com/language-of-love/tristan-welcome.mp3'/>"
    welcome_2 = "<audio src = 'https://s3.amazonaws.com/language-of-love/tristan-welcome-2.mp3'/>"
    fantastico = "<audio src='https://s3.amazonaws.com/language-of-love/tristan-fantastico.mp3'/>"
    mucho_gusto = "<audio src='https://s3.amazonaws.com/language-of-love/tristan-mucho_gusto.mp3'/>"
    pracrice_or_date = "<audio src='https://s3.amazonaws.com/language-of-love/practice_or_speed_date.mp3'/>"